### ISSUE TITLE
Support for GridFieldExtensions 1.1

### ISSUE THREAD

**Issue by christopherdarling** [heyday/silverstripe-gridfieldversionedorderablerows#1]
We have a project with GridFieldExtensions installed (v1.1), when trying to install this via composer it fails due to the version requirement in composer.json ~1.0.0

**Comment by camspiers** [comment]
I have relaxed the version constraints, but I can't confirm that the module is compatible with the newer versions of gridfield extensions.

@stecman can you confirm?

https://packagist.org/packages/heyday/silverstripe-gridfieldversionedorderablerows

**Comment by stecman** [comment]
Thanks, @camspiers - tested and works.

**Comment by christopherdarling** [comment]
Thanks @camspiers working great here too
